Add Selenium Hub & test on chrome, firefox, opera & phantomjs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,6 +18,9 @@ language: perl
 notifications:
   webhooks: https://ledgersmb.org/webhook/travis_ci_notifications
 
+services:
+  - docker
+
 env:
   global:
     - RELEASE_TESTING=1
@@ -25,8 +28,9 @@ env:
     - PGPASSWORD=test
     - LSMB_TEST_DB=1
     - LSMB_NEW_DB=lsmbinstalltest
-    - LSMB_BASE_URL="http://127.0.0.1:5000"
-    - PSGI_BASE_URL="http://127.0.0.1:5762"
+    - DOCKER_GATEWAY_HOST="`hostname -I |awk '{print $1}'`"
+    - LSMB_BASE_URL="http://$DOCKER_GATEWAY_HOST:5000"
+    - PSGI_BASE_URL="http://$DOCKER_GATEWAY_HOST:5762"
     - HARNESS_RULESFILE="t/testrules.yml"
     - PATH=$HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
     - PATH="$HOME/locallib/bin:$PATH"
@@ -40,18 +44,6 @@ env:
 addons:
   apt:
     packages: &default_packages
-      # Install awscli dependencies from the package repo
-      #- python3-pip
-      #- python3-pyasn1
-      #- python3-urllib3
-      #- python3-yaml
-      #- python3-dateutil
-      #- python3-six
-      #- python3-jmespath
-      #- python3-botocore
-      #- python3-rsa
-      #- python3-docutils
-      #- python3-colorama
       - nginx
       - texlive-latex-recommended
       - texlive-xetex
@@ -68,6 +60,7 @@ matrix:
       env:
         - DB_TESTING=1
         - POSTGRESQL=9.6
+        - BROWSER=chrome
     - perl: '5.28'
       addons:
         postgresql: '9.6'
@@ -77,14 +70,17 @@ matrix:
             - postgresql-9.6-pgtap
       env:
         - POSTGRESQL=9.6
-    # - perl: '5.26'
-    #   addons:
-    #     postgresql: '9.6'
-    #     apt:
-    #       packages:
-    #         - *default_packages
-    #         - postgresql-9.6-pgtap
-    #   env:
+        - BROWSER=firefox
+    - perl: '5.26'
+      addons:
+        postgresql: '9.6'
+        apt:
+          packages:
+            - *default_packages
+            - postgresql-9.6-pgtap
+      env:
+        # Driver insists on operablink as browsername but returns opera when asked on capabilities
+        BROWSER=operablink
     - perl: '5.24'
       addons:
         postgresql: '9.6'
@@ -94,7 +90,7 @@ matrix:
             - postgresql-9.6-pgtap
       env:
         - COA_TESTING=1
-        - POSTGRESQL=9.6
+        - BROWSER=phantomjs
 
 before_cache:
   - mkdir -p $HOME/dojo_archive
@@ -132,7 +128,7 @@ install:
   - cpanm --quiet --notest Cpanel::JSON::XS~3.0206
   - cpanm --quiet --notest Starlet
   - cpanm --quiet --notest --metacpan --installdeps --with-develop --with-feature=edi --with-feature=latex-pdf-ps --with-feature=openoffice  --with-feature=starman --with-feature=xls .
-  - cpan-install --coverage
+  - if [ "$COVERAGE" == "1" ] ; then cpan-install --coverage ; fi
 
 before_script:
   - make dist DIST_VER=travis DIST_DIR=${HOME}/built-dist/tar-output
@@ -143,8 +139,20 @@ before_script:
   - cp t/.proverc ./
   - coverage-setup
   - sed -e "s#{ROOT}#$PWD#" doc/conf/webserver/nginx-travis.conf >/tmp/nginx.conf
-  - ((phantomjs --webdriver=4422 2>/dev/null >/dev/null &) && echo "PhantomJS started succesfully") || (echo "Failed to start PhantomJS!" ; exit 1)
-  - PERL5OPT="$PERL5OPT $HARNESS_PERL_SWITCHES" starman --preload-app --pid starman.pid --workers $(test-jobs) -Ilib -Iold/lib --port 5762 bin/ledgersmb-server.psgi --access-log /tmp/plackup-access.log > /tmp/plackup-stdout.log 2> /tmp/plackup-stderr.log &
+  - |
+    if [ "${BROWSER}" == "phantomjs" ];
+    then
+      ((phantomjs --webdriver=4422 2>/dev/null >/dev/null &) && echo "PhantomJS started succesfully") || (echo "Failed to start PhantomJS!" ; exit 1)
+    else
+      docker network create circleci_default
+      docker-compose -f utils/selenium/docker-compose.yml up -d \
+            --scale ${BROWSER}=4
+    fi
+  - PERL5OPT="$PERL5OPT $HARNESS_PERL_SWITCHES" starman --preload-app
+        --pid starman.pid --workers $(test-jobs) -Ilib -Iold/lib
+        --port 5762 bin/ledgersmb-server.psgi
+        --Reload lib,old,xt/lib,t,xt,/usr/local/share/perl,/usr/share/perl,/usr/share/perl5,/home/travis/locallib/lib/perl5
+        --access-log /tmp/plackup-access.log 2> /tmp/plackup-error.log &
   - nginx -c /tmp/nginx.conf
   # display the available resources
   - utils/diagnostics/t/01-system-resources.t
