Ensure W3C compatible Selenium Remote Driver

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -42,6 +42,7 @@ matrix:
       env:
         - POD_TESTING=1
         - BROWSER=chrome
+        - CHROMEDRIVER=2.35
     - perl: '5.24'
       addons:
         postgresql: '9.5'
@@ -56,6 +57,7 @@ matrix:
         # - TEST_SAUCE=1
         - DOJO_BUILT=0
         - BROWSER=firefox
+        - GECKODRIVER=0.19.1
         - MOZ_HEADLESS=1
     - perl: '5.22'
       addons:
@@ -80,6 +82,7 @@ matrix:
       env:
         - COA_TESTING=1
         - BROWSER=firefox
+        - GECKODRIVER=0.19.1
         - MOZ_HEADLESS=1
     - perl: '5.18'
       addons:
@@ -93,6 +96,7 @@ matrix:
       env:
         - DB_TESTING=1
         - BROWSER=chrome
+        - CHROMEDRIVER=2.35
     - perl: '5.16'
       addons:
         postgresql: "9.2"
@@ -105,6 +109,7 @@ matrix:
       env:
         - DB_TESTING=1
         - BROWSER=firefox
+        - GECKODRIVER=0.19.1
         - MOZ_HEADLESS=1
     - perl: '5.14'
       addons:
@@ -145,7 +150,23 @@ before_install:
   - |
     case "${BROWSER}" in
       'chrome')
-          google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
+          wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER}/chromedriver_linux64.zip ;
+          unzip chromedriver_linux64.zip ;
+          sudo chmod +x chromedriver ;
+          sudo mv chromedriver /usr/bin/ ;
+          rm chromedriver_linux64.zip ;
+          a=( ${SELENIUM//./ } );
+          SELENIUM_DIR="${a[0]}.${a[1]}"
+          wget -q http://selenium-release.storage.googleapis.com/${SELENIUM_DIR}/selenium-server-standalone-${SELENIUM}.jar ;
+        ;;
+      'firefox')
+          wget -q https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER}/geckodriver-v${GECKODRIVER}-linux64.tar.gz ;
+          sudo sh -c 'tar -x geckodriver -zf geckodriver-v${GECKODRIVER}-linux64.tar.gz -O > /usr/bin/geckodriver' ;
+          sudo chmod +x /usr/bin/geckodriver ;
+          rm geckodriver-v${GECKODRIVER}-linux64.tar.gz ;
+          a=( ${SELENIUM//./ } );
+          SELENIUM_DIR="${a[0]}.${a[1]}"
+          wget -q http://selenium-release.storage.googleapis.com/${SELENIUM_DIR}/selenium-server-standalone-${SELENIUM}.jar ;
         ;;
     esac
 
@@ -164,6 +185,19 @@ before_script:
   - coverage-setup 2>/dev/null
   - export DEVEL_COVER_OPTIONS=+ignore,"\.lttc\$"
   - sed -e "s#{ROOT}#$PWD#" conf/nginx-travis.conf >/tmp/nginx.conf
+
+  - |
+    case "${BROWSER}" in
+      'phantomjs')
+         phantomjs --version ;
+         ((phantomjs --webdriver=4422 2>/dev/null >/dev/null &) && echo "PhantomJS started succesfully") || (echo "Failed to start PhantomJS!" ; exit 1)
+      ;;
+      'chrome' | 'firefox')
+        sh -e /etc/init.d/xvfb start ;
+        java -jar selenium-server-standalone-${SELENIUM}.jar 2>/tmp/selenium.log >/dev/null -port 4422 &
+      ;;
+    esac
+
   - PERL5OPT="$PERL5OPT $HARNESS_PERL_SWITCHES" plackup -Ilib --port 5001 --server HTTP::Server::PSGI tools/starman.psgi --access_log /tmp/plackup-access.log 2> /tmp/plackup-error.log &
   - utils/test/Is_LSMB_running.sh --early # fail early if starman is not running (can be skipped based on reponame or owner by setting an array in the script)
   - nginx -c /tmp/nginx.conf
@@ -172,6 +206,9 @@ before_script:
   - utils/diagnostics/t/01-system-resources.t
   # Patch Weasel for a test of S::R::D 1.23
   - sudo cp utils/test/*.pm /home/travis/locallib/lib/perl5/Weasel/Driver/
+  - phantomjs --version
+  - firefox --version
+  - chrome --version
 
 script:
   - RELEASE_TESTING=1
